### ISSUE TITLE
Byte Array icon

### ISSUE THREAD

**Issue by hot202xu1** [Soundux/traypp#2]
Add the option to be able to use byte array icons for both Linux / windows. 
also windows should be able to use the icon from file not just resource.

**Comment by Curve** [comment]
Not sure if I can allow windows users to load the icon from a file instead of a resource but loading the icon from a byte array is not possible with appindicator (linux)

**Comment by Curve** [comment]
I added the possibility to load icons from a file or an existing HICON.

If you still want to load your icon from memory you can do so by calling `CreateIconFromResourceEx` and passing the returned HICON to the constructor

**Comment by hot202xu1** [comment]
Thanks for the fast reply. 
one other small option that you could add is separators

**Comment by Curve** [comment]
Yeah thought about that too, I will add them today

**Comment by hot202xu1** [comment]
Thanks. Good work.

**Comment by Curve** [comment]
I added separators
