### ISSUE TITLE
To add plain text to tray menu

### ISSUE THREAD

**Issue by thirtyninekilovolts** [Soundux/traypp#3]
There can be the addable menu, submenu a synced/toggle button. I think anyone can need to add just plain text which can be used to show the version of software.

By the way, I have already patched on my local, if you would like me to contribute repo, I can gladly do it.

**Comment by Curve** [comment]
I will look into this, should be easy to implement

> By the way, I have already patched on my local, if you would like me to contribute repo, I can gladly do it.
If you have it implemented for Windows as well as Linux feel free to open a pr

**Comment by Curve** [comment]
Would you want a Label to look like this:

![image](https://user-images.githubusercontent.com/37805707/115082811-c9408100-9f06-11eb-85b9-620c0c81135f.png)

Or just like a normal button where nothing happens when you press it?

**Comment by thirtyninekilovolts** [comment]
yep! It is just the same mine. I think no need to make it clickable or has. Otherwise, It is already being a button item again. Thank you again.
